before:
  hooks:
    - go mod tidy

builds:
  - main: ./main.go
    binary: pmesh
    id: pmesh
    env:
      - CGO_ENABLED=0
    goos: [ windows,linux,darwin ]
      goarch: [ amd64,arm64 ]

archives:
  - format: zip
      id: pmesh
      builds: [ pmesh ]
      replacements:
        darwin: macOS

checksum:
  algorithm: sha256
