before:
  hooks:
    - go mod tidy

builds:
  - main: ./main.go
    id: pmesh
    binary: pmesh
    goos: [windows, linux, darwin]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0

archives:
  - format: zip
    id: pmesh
    builds: [pmesh]
    replacements:
      darwin: macOS

checksum:
  algorithm: sha256
